defaults:
  - model: mlp
  - model_downstream: mlp
  - dataset: california_housing
  - hyp: hyp_for_neural_network
  - hyp_downstream: hyp_for_neural_network
  - override hydra/job_logging: custom
  - _self_


hydra:
  sweep:
    dir: ./outputs/optuna/${name}/tuning-${model.name}-${dataset.name}-noise_${dataset.add_noise}-percent_${dataset.noise_percent}
    subdir: ${hyp.seed} # results will be saved in {hyp.seed} subfolder
  job_logging:
    handlers:
      file:
        filename: train.log

train_log: train_log
name: ''                                   # name of the experiment (for saving the results)
mode: 'feature_selection'                  # mode for training a model. Options: ['downstream', 'feature_selection'].
importance_path: feature_importances.pt    # if mode=='downstream' and importance_path is not None, then feature_importance will be used for selecting topk features
topk: