epochs: 200
lr: 0.001
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 40
  - 80
optimizer: adamw
patience: 20
save_period: -1
seed: 1
test_batch_size: 512
train_batch_size: 512
use_patience: true
val_period: 20
warmup_period: 5
weight_decay: 2e-4
momentum: 0.9
warmup_type: linear
regularization:
reg_weight:
add_noise:
noise_percent:

